spring:
  profiles:
    active: dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.16.39.93:3306/decontroler_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8
    username: ads
    password: Welcome2sohu!

server:
  servlet:
    context-path: /hush
  port: 8900

mybatis:
  default-statement-timeout: 30
  type-aliases-package: com.hush.web.mybatis.model
  mapper-locations: classpath:mappers/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql